/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Link from "next/link";
import { api } from "../services/api";
import { PokeContext } from "@/context/PokeContext";
import { useContext, useEffect, useState } from "react";
import SearchBar from "@/components/SearchBar";
import Image from "next/image";
import logo from "../../public/logoPokedex.png";

interface IPokemon {
  name: string;
  url: string;
}

export default function Home() {
  const { wordToSearch } = useContext(PokeContext);

  const [pokemonList, setmokemonList] = useState<IPokemon[]>([]);
  const [loading, setloading] = useState(false);

  useEffect(() => {
    setloading(true);
    async function getPokemon() {
      const response = await api.get("pokemon", {
        params: {
          limit: 1281,
          offset: 0,
        },
      });
      if (wordToSearch === "") {
        setmokemonList(response.data.results);
      } else {
        const filteredPokemon = response.data.results.filter(
          (pokemon: IPokemon) => {
            return pokemon.name
              .toLowerCase()
              .includes(wordToSearch.toLocaleLowerCase());
          }
        );
        setmokemonList(filteredPokemon);
      }
    }
    getPokemon();
  }, [wordToSearch]);

  return (
    <>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon2.ico" />
      </Head>
      <main className="mainIndex">
        <div className="box">
          <Image src={logo} alt="Pokemon" width={300} />
          <SearchBar />
          <ul className="list">
            {pokemonList!.map((pokemon) => {
              return (
                <li key={pokemon.name}>
                  <Link href={`/pokemon/${pokemon.name}`}>
                    <div className="card">
                      <img
                        src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${pokemon.url.slice(
                          34,
                          -1
                        )}.png`}
                        alt={pokemon.name}
                        width={100}
                        height={100}
                      />
                      <h3>
                        {pokemon.name[0].toUpperCase() +
                          pokemon.name.substring(1)}
                      </h3>
                    </div>
                  </Link>
                </li>
              );
            })}
          </ul>
        </div>
      </main>
    </>
  );
}

//está acontecendo no backend
// export async function getStaticProps() {
//   // const res = await fetch("https://pokeapi.co/api/v2/pokemon?limit=151&offset=0");
//   // const { results: pokemonList } = await res.json();

//   const response = await api.get("pokemon",{
//     params:{
//       limit:1281,
//       offset:0,
//     }
//   })
//   return {
//     props: {
//       pokemonList: response.data.results,
//     },
//     revalidate: 60 * 60 * 12,
//   };
// }

// export async function getServerSideProps() {
//   const res = await fetch(
//     "https://pokeapi.co/api/v2/pokemon?limit=151&offset=0"
//   );
//   const { results: pokemonList } = await res.json();
//   return {
//     props: {
//       pokemonList,
//     },
//   };
// }
