import Head from "next/head";
import { useEffect, useState } from "react";
// import styles from "@/styles/Home.module.css";

interface IPokemon {
  name: string;
  url: string;
}

interface IHomeProps {
  pokemonList: IPokemon[];
}

export default function Home({ pokemonList }: IHomeProps) {
  

  // useEffect(()=>{},[])
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>Página inicial</h1>
          <ul>
            {pokemonList.map((pokemon) => {
              return (
                <li key={pokemon.name}>
                  <h3>{pokemon.name}</h3>
                </li>
              );
            })}
          </ul>
        </div>
      </main>
    </>
  );
}


//está acontecendo no backend
// export async function getStaticProps() {
//   const res = await fetch(
//     "https://pokeapi.co/api/v2/pokemon?limit=151&offset=0"
//   );
//   const { results: pokemonList } = await res.json();
//   return {
//     props: {
//       pokemonList,
//     },
//     revalidate: 60 * 60 *12
//   };
// }

export async function getServerSideProps() {
  const res = await fetch(
    "https://pokeapi.co/api/v2/pokemon?limit=151&offset=0"
  );
  const { results: pokemonList } = await res.json();
  return {
    props: {
      pokemonList,
    },
  };
}